# GitVote configuration file reference: https://github.com/cncf/gitvote/blob/main/docs/config/.gitvote.yml

profiles:
  default:
    duration: 4w
    pass_threshold: 51
    allowed_voters:
      teams:
        - gitvote-steering
      exclude_team_maintainers: false
    periodic_status_check: 1 week
    close_on_passing: true

# Automation (optional)
#
# Create votes automatically on PRs when any of the files affected by the PR
# match any of the patterns provided. Patterns must follow the gitignore
# format (https://git-scm.com/docs/gitignore#_pattern_format).
#
# Each automation rule must include a list of patterns and the profile to use
# when creating the vote. This allows creating votes automatically using the
# desired configuration based on the patterns matched. Rules are processed in
# the order provided, and the first match wins.
#
automation:
  enabled: true
  rules:
    - patterns:
        - "/resolutions/proposed/*.md"
      profile: default
