= Charter of The TODO Group

:toc:

 . *Mission of the TODO Group (“TODO”).*
 The TODO Group’s mission is to identify key policy and process choices related to corporate open source engagement and create tools and educational materials that promote best practices around such engagements.
 . *General Membership*
The TODO Group membership is composed of individuals deeply involved in running open source programs, tasked to drive open source across divisions and product lines within their organization. These individuals have learned from practical experience what it takes to successfully engage in or create open source projects and build effective internal open source programs that guide how developers in their company engage in external communities. +
The TODO Group's general membership shall be composed of the General Members and a Steering Committee. Anyone may participate as a General Member as long as they meet the General Member Qualifications. At such time as a General Member no longer meets the qualifications, their General Member status will be rescinded.
 .. General Member Qualifications: An individual may be qualified to join TODO Group as a General Member if they:
 ... Are an employee of an organization that is a member of The Linux Foundation at any membership level.
 ... Are an employee of an organization with development teams that use or contribute to open source projects across multiple divisions, products, or departments,
 ... in a role that manages, oversees, or guides the organization’s policies and contributions to open source projects (an “Open Source Program Office”),
 ... and the organization does not derive a significant portion of its revenue as a solution provider to other OSPOs. +
 .. General Members shall be entitled to:
 ... Participate in TODO Group Working Groups, meetings, initiatives, events and any other activities;
 ... identify their company as a member or participant in the TODO Group; and
 ... nominate one individual for election to the Steering Committee.
 . *Steering Committee*
 .. Responsibility: The Steering Committee shall be responsible for:
 ... coordinating with the group's Program Manager to manage day-to-day operations of the group;
 ... overseeing all business and marketing matters, including approving new programs and initiatives that make use of the TODO Group name, logo, or branding, and approving use of the TODO Group name, logo, or branding for sponsorship or endorsement purposes;
 ... approving, modifying or eliminating Working Groups;
 ... adopting and maintaining policies, rules, and/or procedures for the group (subject to LF approval) including but not limited to a Code of Conduct, a trademark policy and any other policies;
 ... approving procedures for the nomination, election, and appointment of Steering Committee members;
 ... approving procedures for the nomination and election of any officer or other positions created by the Steering Committee;
 ... voting on all decisions or matters coming before the Steering Committee.
 .. Composition:
 ... Steering Committee members shall be nominated or appointed for their expertise, contribution to the advancement of open source program management, and diversity of backgrounds and opinions.
 ... The Steering Committee shall be composed of seven (7) General Members, with five (5) elected and two (2) appointed.
 ... Committee member terms shall begin on January 1st of the year following election or appointment, and terminate on December 31st of the second year following election or appointment.
 ... In each calendar year, the group shall hold an election to fill elected positions which will be vacated at the end of that year. The election process shall include nominations and voting during the month of September.
 ... In each calendar year, the committee shall appoint one (1) member to fill the appointed position which will be vacated at the end of that year. The appointment shall be made during the month of October, by the current members of the commitee at that time.
 ... In even-numbered years, two (2) elected positions and one (1) appointed position shall be filled by the election and appointment processes.
 ... In odd-numbered years, three (3) elected positions and one (1) appointed position shall be filled by the election and appointment processes.
 ... If any committee member should resign or otherwise be unable to complete their term for any reason, with more than six (6) months remaining in their term, the remaining committee members may appoint a replacement member. For election or appointment purposes, that member's term will end when the outgoing member's term would have ended.
 ... If any committee member should resign or otherwise be unable to complete their term for any reason, with six (6) months or fewer remaining in their term, their position will be left unfilled until the regularly scheduled election or appointment process for that position.
 ... Elections shall be run using the Condorcet-IRV method through the Cornell online service (+++<u>+++http://civs.cs.cornell.edu/+++</u>+++). The methodology or service used in future elections may be changed via a five (5) member approval vote of current members of the committee at that time.
 .. Removal:
 ... Steering Committee members shall qualify for removal for:
 .... Violation of the TODO Group Code of Conduct.
 .... Inexcused absence from two (2) consecutive Steering Committee meetings.
 .... Non-participation in Steering Committee votes and activities via email, real-time chat, or in person for more than consecutive 8 weeks.
 ... The Steering Committee may choose to remove qualifying members by a majority vote of all remaining current members.
 .. Any issues that the Steering Committee is unable to resolve shall be referred to The Linux Foundation for resolution.
 . *Officers*
The Steering Committee shall elect a Chairperson and, if so desired, may elect such other officers as it may choose. All officers shall be elected annually. There are no limits on the number of terms an officer may serve.
 . *Voting*
Actions of the Steering Committee may be taken at in-person meetings, via conference call, or through electronic means, including email or real-time chat. In order for any action to be effective, it shall be approved by a simple majority of the Steering Committee members participating in person and/or by conference call, when a quorum is so present. Quorum shall be met when at least five (5) members of the Steering Committee are present. Any vote may be taken without a meeting electronically but shall require a majority of the entire Steering Committee to pass.
 . *Working Groups*
The TODO Group will host Working Groups for members to contribute to that are intended to accelerate its mission. Initial Working Groups are expected to cover topics including, but not limited to:
 * Well documented software to facilitate the management of open source software engagement by an organization
 * Blog and wiki articles providing recommendations on how to manage open source engagement by an organization
 . *Operating Principles*
 .. TODO member meeting mechanisms and expected frequency
 ... Member meetings may take place via electronic means or face-to-face. Face-to-face meeting locations and times will be set by the Steering Committee.
 ... Meetings will occur at least once per quarter.
 ... Details of meeting mechanisms and instructions for attendance will be published reasonably in advance to all members in good standing.
 .. Communication mechanisms
 ... All public communication not during meetings will take place over the public group mailing list(s), real-time chats, issue trackers, or source code management systems and will be accessible to members and non-members alike.
 ... All private communication not during meetings will take place over the private group mailing list, real-time chat, and GitHub and access will be limited to members only.
 .. Level of confidentiality
 ... All communication during meetings will be under+++<u>+++ Chatham House Rules+++</u>++++++<u>+++.+++</u>+++
 ... All private communication via all media as defined above will be restricted to members only and not permitted for public distribution.
 ... All communication via all media as defined above will be public.
 . *Antitrust Guidelines*
 .. All members shall abide by The Linux Foundation Antitrust Policy available at: https://www.linuxfoundation.org/antitrust-policy/.
 .. All members may encourage open participation from any organization able to meet the membership requirements, regardless of competitive interests. Put another way, the TODO Group shall not seek to exclude members based on any criteria, requirements, or reasons other than those used for all members.
 . *General Rules and Operations*.
The TODO Group shall be conducted so as to:
 .. engage in the work of the project in a professional manner consistent with maintaining a cohesive community, while also maintaining the goodwill and esteem of The Linux Foundation in the open source software community;
 .. respect the rights of all trademark owners, including any branding and usage guidelines;
 .. engage The Linux Foundation for all TODO press and analyst relations activities;
 .. upon request, provide information regarding Project participation, including information regarding attendance at Project-sponsored events, to The Linux Foundation;
 .. coordinate with The Linux Foundation in relation to any websites created directly for TODO; and
 .. operate under such rules and procedures as may from time to time be approved by the Steering Committee and confirmed by The Linux Foundation.
 .. Under no circumstances shall The Linux Foundation be expected or required to undertake any action on behalf of TODO that is inconsistent with the tax exempt purpose of The Linux Foundation.
 . *Intellectual Property Policy*
 .. All contributions shall be accompanied by a Developer Certificate of Origin sign-off (http://developercertificate.org).
 .. All new inbound code contributions to TODO shall be made under the Apache License, Version 2.0 (available at http://www.apache.org/licenses/LICENSE-2.0) or an alternative OSI-approved open source license clearly identified by the contributor in the contribution in accordance with the DCO. All documentation will be contributed to and made available to TODO under the Creative Commons Attribution 4.0 International License (available at http://creativecommons.org/licenses/by/4.0/) or an alternative OSI-approved open source license clearly identified by the contributor in the contribution in accordance with the DCO.
 .. All outbound code will be made available under the license for the inbound contribution.
 .. Any TODO member may raise an objection or concern regarding any contribution made under an alternative license to the Steering Committee for resolution.

 . *Amendments and Notice*
 .. This Charter may be amended, and additional rules may be adopted, at any time by a two-thirds majority of all then serving Steering Committee members with final approval from The Linux Foundation.
